### ISSUE TITLE
"conan install" doesn't work in testing environment on Ubuntu 22.04

### ISSUE THREAD

**Issue by nouvak** [conan-io/training#102]
Hello!

When executing "conan install .." command of the "consumer" exercise in the conan-training docker container, I get the following error:

ERROR: boost/1.72.0: Cannot load recipe.
Error loading conanfile at '/home/conan/.conan/data/boost/1.72.0/_/_/export/conanfile.py': Unable to load conanfile in /home/conan/.conan/data/boost/1.72.0/_/_/export/conanfile.py
  File "/opt/pyenv/versions/3.7.13/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/conan/.conan/data/boost/1.72.0/_/_/export/conanfile.py", line 1, in <module>
    from conan.tools.apple import is_apple_os
ImportError: cannot import name 'is_apple_os' from 'conan.tools.apple' (/opt/pyenv/versions/3.7.13/lib/python3.7/site-packages/conan/tools/apple/__init__.py)

I resolved the error by upgrading the conan package to 1.52.0 version:
pip install conan --upgrade

You might want to consider upgrading the conan version in the conan-training Docker container.

Greetings
   Marko Novak

**Comment by wickywaka** [comment]
I hit this issue on windows 11. The docker is running on WSL2 and `pip install conan --upgrade` fixed the issue. Just leaving a comment here in case you guys forgot the merge request. This can throw off a beginner off course.

**Comment by uilianries** [comment]
Hello, the pull request #103 should update Conan 1.52.0

**Comment by memsharded** [comment]
https://github.com/conan-io/training/pull/103 was merged, re-building the docker should work now, thanks!
